<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>LegacyUIFramework.Example</AssemblyName>
    <RootNamespace>BigCityLegacy.UI.Example</RootNamespace>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

	<!--
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Set GameDir + GameDataDir, or set ManagedDir and BepInExDir directly.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	-->
	<GameDir Condition="'$(GameDir)' == ''">..\..\..\..\..\10_game</GameDir>
	<GameDataDir Condition="'$(GameDataDir)' == ''">game_Data</GameDataDir>
	<ManagedDir Condition="'$(ManagedDir)' == ''">$(GameDir)\$(GameDataDir)\Managed</ManagedDir>
	<BepInExDir Condition="'$(BepInExDir)' == ''">$(GameDir)\BepInEx\core</BepInExDir>
	  
    <CopyToPlugins Condition="'$(CopyToPlugins)' == ''">false</CopyToPlugins>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;0618;0649</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;0618;0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LegacyUIFramework.net35\LegacyUIFramework.net35.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyPluginToGame" AfterTargets="Build" Condition="'$(CopyToPlugins)' == 'true'">
    <MakeDir Directories="$(GameDir)\BepInEx\plugins\LegacyUIFramework.Example" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameDir)\BepInEx\plugins\LegacyUIFramework.Example" />
    <Copy SourceFiles="$(OutputPath)LegacyUIFramework.dll" DestinationFolder="$(GameDir)\BepInEx\plugins\LegacyUIFramework.Example" Condition="Exists('$(OutputPath)LegacyUIFramework.dll')" />
  </Target>
</Project>
